"""initial schema

Cobre as 9 tabelas da Market Data Platform: countries, sectors_gics,
companies, assets, trading_calendar, prices_daily, financial_statements,
valuation_multiples, ingestion_log. Gerado via `alembic revision
--autogenerate` a partir de `backend.db.schema.Base.metadata` contra um
SQLite vazio. Os blocos `batch_alter_table` são gerados pelo autogenerate
para compatibilidade com SQLite (`render_as_batch=True` em env.py); em
Postgres rodam como `CREATE INDEX` normal.

Ajuste manual sobre o autogenerate: o `downgrade()` original deixava os
três tipos ENUM do Postgres (`assettype`, `periodtype`, `ingestionstatus`)
órfãos após `drop_table`, quebrando o round-trip upgrade→downgrade→upgrade
em Postgres. Adicionado drop explícito desses tipos no fim do downgrade
(`checkfirst=True` torna no-op em SQLite, onde o ENUM vira CHECK
constraint embutido na tabela).

Revision ID: 1a4f86d9547c
Revises:
Create Date: 2026-04-29 23:42:07.521253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4f86d9547c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Tipos ENUM do schema. Definidos no nível do módulo para reuso entre
# create_table (alembic injeta automaticamente) e o cleanup do downgrade.
_assettype_enum = sa.Enum(
    'stock', 'index', 'commodity', 'fx', 'crypto', 'etf',
    name='assettype',
)
_periodtype_enum = sa.Enum('quarterly', 'annual', name='periodtype')
_ingestionstatus_enum = sa.Enum(
    'success', 'error', 'partial', name='ingestionstatus',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_pt', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('main_exchange', sa.String(length=50), nullable=True),
    sa.Column('yf_suffix', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('iso3')
    )
    op.create_table('ingestion_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('ingestion_type', sa.String(length=30), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', 'partial', name='ingestionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.create_index('ix_ingestion_log_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_ingestion_log_status', ['status'], unique=False)
        batch_op.create_index('ix_ingestion_log_symbol', ['symbol'], unique=False)

    op.create_table('sectors_gics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('sector_pt', sa.String(length=100), nullable=True),
    sa.Column('industry_group', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('sub_industry', sa.String(length=200), nullable=True),
    sa.Column('gics_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sectors_gics', schema=None) as batch_op:
        batch_op.create_index('ix_sectors_gics_gics_code', ['gics_code'], unique=False)
        batch_op.create_index('ix_sectors_gics_sector', ['sector'], unique=False)

    op.create_table('trading_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('is_business_day', sa.Boolean(), nullable=True),
    sa.Column('holiday_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'exchange', name='uq_calendar_date_exchange')
    )
    with op.batch_alter_table('trading_calendar', schema=None) as batch_op:
        batch_op.create_index('ix_trading_calendar_date', ['date'], unique=False)
        batch_op.create_index('ix_trading_calendar_exchange', ['exchange'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('sector_gics_id', sa.Integer(), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['sector_gics_id'], ['sectors_gics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('ix_companies_country_id', ['country_id'], unique=False)
        batch_op.create_index('ix_companies_sector_gics_id', ['sector_gics_id'], unique=False)
        batch_op.create_index('ix_companies_ticker', ['ticker'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('asset_type', sa.Enum('stock', 'index', 'commodity', 'fx', 'crypto', 'etf', name='assettype'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_asset_type', ['asset_type'], unique=False)
        batch_op.create_index('ix_assets_symbol', ['symbol'], unique=False)

    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Enum('quarterly', 'annual', name='periodtype'), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_of_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capex', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_end', 'period_type', name='uq_financials_company_period')
    )
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.create_index('ix_financial_statements_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_financial_statements_period_end', ['period_end'], unique=False)

    op.create_table('valuation_multiples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ps_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ev_revenue', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('payout_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_debt_ebitda', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'snapshot_date', name='uq_valuation_company_date')
    )
    with op.batch_alter_table('valuation_multiples', schema=None) as batch_op:
        batch_op.create_index('ix_valuation_multiples_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_valuation_multiples_snapshot_date', ['snapshot_date'], unique=False)

    op.create_table('prices_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_prices_asset_date')
    )
    with op.batch_alter_table('prices_daily', schema=None) as batch_op:
        batch_op.create_index('ix_prices_daily_asset_date', ['asset_id', 'date'], unique=False)
        batch_op.create_index('ix_prices_daily_asset_id', ['asset_id'], unique=False)
        batch_op.create_index('ix_prices_daily_date', ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_prices_daily_date')
        batch_op.drop_index('ix_prices_daily_asset_id')
        batch_op.drop_index('ix_prices_daily_asset_date')

    op.drop_table('prices_daily')
    with op.batch_alter_table('valuation_multiples', schema=None) as batch_op:
        batch_op.drop_index('ix_valuation_multiples_snapshot_date')
        batch_op.drop_index('ix_valuation_multiples_company_id')

    op.drop_table('valuation_multiples')
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_statements_period_end')
        batch_op.drop_index('ix_financial_statements_company_id')

    op.drop_table('financial_statements')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_symbol')
        batch_op.drop_index('ix_assets_asset_type')

    op.drop_table('assets')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('ix_companies_ticker')
        batch_op.drop_index('ix_companies_sector_gics_id')
        batch_op.drop_index('ix_companies_country_id')

    op.drop_table('companies')
    with op.batch_alter_table('trading_calendar', schema=None) as batch_op:
        batch_op.drop_index('ix_trading_calendar_exchange')
        batch_op.drop_index('ix_trading_calendar_date')

    op.drop_table('trading_calendar')
    with op.batch_alter_table('sectors_gics', schema=None) as batch_op:
        batch_op.drop_index('ix_sectors_gics_sector')
        batch_op.drop_index('ix_sectors_gics_gics_code')

    op.drop_table('sectors_gics')
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.drop_index('ix_ingestion_log_symbol')
        batch_op.drop_index('ix_ingestion_log_status')
        batch_op.drop_index('ix_ingestion_log_started_at')

    op.drop_table('ingestion_log')
    op.drop_table('countries')
    # ### end Alembic commands ###

    # Cleanup explícito dos tipos ENUM (Postgres). No SQLite os ENUM viram
    # CHECK constraints embutidos na tabela e já foram removidos pelo
    # drop_table; checkfirst=True deixa este passo no-op nesse caso.
    bind = op.get_bind()
    _assettype_enum.drop(bind, checkfirst=True)
    _periodtype_enum.drop(bind, checkfirst=True)
    _ingestionstatus_enum.drop(bind, checkfirst=True)
