"""add watchlist tables

ISSUE-018. Adiciona `user_sessions` (sessão anônima por cookie UUID) e
`watchlist_items` (asset_id × session_uuid com UNIQUE para idempotência).
Migração puramente aditiva — não toca nas 9 tabelas existentes.
Round-trip up→down→up validado em SQLite (CI) e testado em
`tests/test_alembic_migration.py`.

Revision ID: 77b6af8de3dd
Revises: 1a4f86d9547c
Create Date: 2026-04-30 15:43:39.416902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b6af8de3dd'
down_revision: Union[str, None] = '1a4f86d9547c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_uuid', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_uuid'], ['user_sessions.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_uuid', 'asset_id', name='uq_watchlist_session_asset')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index('ix_watchlist_items_asset_id', ['asset_id'], unique=False)
        batch_op.create_index('ix_watchlist_items_session_uuid', ['session_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index('ix_watchlist_items_session_uuid')
        batch_op.drop_index('ix_watchlist_items_asset_id')

    op.drop_table('watchlist_items')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
